<article class='page'>
    <h2>Um... ok...</h2>
    <div class='story'>
        <p>
          So, um, you appear to have picked a choice that does not actually
          exist in our database... Nice work!
        </p>
        <p>
          There is not much else you can do now but go back to home...
          (or use your back button!)
        </p>
    </div>
    <ul class='choices'>
        <li><a href='<?php echo $this->url('home'); ?>'>Back to home...</a></li>
    </ul>
</article>
