<?php if (isset($page)): ?>
    <article class='page' id='page<?php $page->id; ?>'>
        <h2><?php echo $page->title; ?></h2>
        <div class='story markdown'>
            <?php echo $this->page($page->getStory()); ?>
        </div>
        <ul class='choices'>
          <?php foreach ($page->getChoices() as $oChoice): ?>
            <?php if (!$oChoice->checkChance()) continue; ?>
            <li><a href='<?php echo $this->url('choice', Array('id' => $oChoice->id)); ?>'><?php echo $oChoice->description; ?></a></li>
          <?php endforeach; ?>
        </ul>
    </article>
<?php else: ?>
    <article class='page'>
        <h2>Um... ok...</h2>
        <div class='story'>
            <p>
              So, um, you appear to have requested a page that does not actually
              exist in our database... Nice work!
            </p>
            <p>
              There is not much else you can do now but go back to home...
              (or use your back button!)
            </p>
        </div>
        <ul class='choices'>
            <li><a href='<?php echo $this->url('home'); ?>'>Back to home...</a></li>
        </ul>
    </article>
<?php endif; ?>
