<?php
$this->headTitle()->setSeparator(' - ')
                  ->setAutoEscape(false);

echo $this->doctype()."\n";
?>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <?php echo $this->headTitle('Write Your Own Adventure')."\n"; ?>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" >

    <!-- Styles -->
    <link href='http://fonts.googleapis.com/css?family=Ubuntu+Mono|Ubuntu:400,700,400italic' rel='stylesheet' type='text/css'>
    <link href="<?php echo $this->basePath('/css/styles.less'); ?>" rel="stylesheet/less" type="text/css" >
    <script type="text/javascript" src="<?php echo $this->basePath('/js/less.min.js'); ?>"></script>

    <!-- Scripts -->
    <!--[if lt IE9]> <script type="text/javascript" src="<?php echo $this->basePath('/js/html5.js'); ?>"></script><![endif]-->
  </head>

  <body>

    <header>
      <h1>
        <a href='<?php echo $this->url('home'); ?>'>Write Your Own Adventure</a>
        <small>The collaborative 'choose your own adventure' generator.</small>
      </h1>
    </header>

    <div class='content'>
      <div class='pages'>
        <?php echo $this->content; ?>
      </div><div class='extras'>
        <aside>
            <h3>The story so far...</h3>
            <ol>
                <li><a href='#'>Once upon a time...</a></li>
                <li><a href='#'>Three little pigs</a></li>
                <li><a href='#'>Blah</a></li>
                <li><a href='#'>Three little pigs</a></li>
                <li><a href='#'>Once upon a time...</a></li>
                <li><a href='#'>Three little pigs</a></li>
                <li><a href='#'>Blah</a></li>
                <li><a href='#'>Three little pigs</a></li>
            </ol>
        </aside><aside>
            <h3>Page Information</h3>
            <ul>
                <li>Page #123</li>
                <li>Last Updated: 2012-01-01</li>
                <li>Backlinks: <a href='#'>1</a></li>
            </ul>
        </aside><aside>
            <h3>User Information</h3>
            <p><em>Not logged in</em></p>
        </aside>
      </div>
    </div>

    <footer>
        <p>
            <a rel="license" href="http://creativecommons.org/licenses/by-nc-sa/3.0/"><img alt="Creative Commons Licence" style="border-width:0" src="http://i.creativecommons.org/l/by-nc-sa/3.0/88x31.png" /></a>
            <br />
            All user content is licensed under a <a rel="license" href="http://creativecommons.org/licenses/by-nc-sa/3.0/">Creative Commons Attribution-NonCommercial-ShareAlike 3.0 Unported License</a>.
            <br />
            <strong>"Write Your Own Adventure"</strong> was created by <a href='http://stephen.rees-carter.net/'>Stephen Rees-Carter</a>
            and can be found on <a href='https://github.com/valorin/wyoa'>Github</a>.
        </p>
    </footer>
</body>
</html>
