<?php
use ValCommon\Tools\Setting;

$this->headTitle()->setSeparator(' - ')
                  ->setAutoEscape(false);

echo $this->doctype()."\n";
?>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <?php echo $this->headTitle(Setting::get('title'))."\n"; ?>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" >

    <!-- Styles -->
    <link href='http://fonts.googleapis.com/css?family=Ubuntu+Mono|Ubuntu:400,700,400italic' rel='stylesheet' type='text/css'>
    <link href="<?php echo $this->basePath('/css/styles.css'); ?>" rel="stylesheet" type="text/css" >
<?php /*
    <link href="<?php echo $this->basePath('/css/styles.less'); ?>" rel="stylesheet/less" type="text/css" >
    <script type="text/javascript" src="<?php echo $this->basePath('/js/less.min.js'); ?>"></script>
*/ ?>

    <!-- Scripts -->
    <!--[if lt IE9]> <script type="text/javascript" src="<?php echo $this->basePath('/js/html5.js'); ?>"></script><![endif]-->
  </head>

  <body>

    <header>
      <h1>
        <a href='<?php echo $this->url('home'); ?>'><?php echo Setting::get('title'); ?></a>
        <small><?php echo Setting::get('tagline'); ?></small>
      </h1>
    </header>

    <div class='content'>
      <div class='pages'>
        <?php echo $this->content; ?>
      </div><div class='extras'>
        <aside class='history'>
            <?= $this->history((isset($oPage) ? $oPage : null)); ?>
        </aside><aside class='page-info'>
            <h3>Page Information</h3>
          <?php if (isset($oPage)): ?>
            <ul>
                <li>Page #<?php echo $oPage->id; ?></li>
                <li>Visits: <?php echo $oPage->visits; ?></li>
                <li>Created: <?php echo $oPage->created; ?></li>
                <li>Created by: <?php echo $oPage->user_id; ?></li>
                <li>Updated: <?php echo $oPage->updated; ?></li>
                <li>Updated by: </li>
                <!-- <li><a href='#edit'>Edit Page</a></li> -->
            </ul>
          <?php else: ?>
            <p><em>No page information to display.</em></p>
          <?php endif; ?>
        </aside><aside class='user-info'>
            <h3>User Information</h3>
            <p><em>Not logged in.</em></p>
        </aside>
      </div>
    </div>

    <footer>
        <p>
            <a rel="license" href="http://creativecommons.org/licenses/by-nc-sa/3.0/"><img alt="Creative Commons Licence" style="border-width:0" src="http://i.creativecommons.org/l/by-nc-sa/3.0/80x15.png" /></a>
            <br />
            All <strong>"<?php echo Setting::get('title'); ?>"</strong> user content is licensed under a <a rel="license" href="http://creativecommons.org/licenses/by-nc-sa/3.0/">Creative Commons Attribution-NonCommercial-ShareAlike 3.0 Unported License</a>.
            <br />
            <strong>"<?php echo Setting::get('title'); ?>"</strong> was created by <a href='http://stephen.rees-carter.net/'>Stephen Rees-Carter</a>
            and can be found on <a href='https://github.com/valorin/wyoa'>Github</a>.
        </p>
    </footer>
</body>
</html>
